name: Build Workflow
env:
  NODE_ENV: ${{ secrets.NODE_ENV }}
  MYSQL_HOST_PROD: ${{ secrets.MYSQL_HOST_PROD }}
  MYSQL_PORT_PROD: ${{ secrets.MYSQL_PORT_PROD }}
  MYSQL_USER_PROD: ${{ secrets.MYSQL_USER_PROD }}
  MYSQL_PASSWORD_PROD: ${{ secrets.MYSQL_PASSWORD_PROD }}
  MYSQL_DATABASE_PROD: ${{ secrets.MYSQL_DATABASE_PROD }}

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]
  workflow_call:
  workflow_dispatch:

jobs:
  test-build:
    name: Test and Build
    runs-on: ubuntu-latest
    outputs:
      success: ${{ steps.build.outputs.success }}
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.0

      - name: Install Dependencies
        run: bun install

      - name: Run TypeScript Check
        run: bun tsc --noEmit

      - name: Run ESLint
        run: bun eslint

      - name: Build Next.js
        id: build
        run: |
          bun next build --webpack
          echo "success=true" >> $GITHUB_OUTPUT
