name: Build Workflow

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  test-build:
    name: Test and Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.0

      - name: Install Dependencies
        run: bun install

      - name: Set Database Variables
        run: |
          echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> $GITHUB_ENV
          echo "HOST_PROD=${{ secrets.HOST_PROD }}" >> $GITHUB_ENV
          echo "PORT_PROD=${{ secrets.PORT_PROD }}" >> $GITHUB_ENV
          echo "USER_PROD=${{ secrets.USER_PROD }}" >> $GITHUB_ENV
          echo "PASSWORD_PROD=${{ secrets.PASSWORD_PROD }}" >> $GITHUB_ENV
          echo "DATABASE_PROD=${{ secrets.DATABASE_PROD }}" >> $GITHUB_ENV

      - name: Run TypeScript Check
        run: npx tsc --noEmit

      - name: Run ESLint
        run: bun eslint

      - name: Build Next.js
        run: bun next build
